### ISSUE TITLE
failed load std packages

### ISSUE THREAD

**Issue by LazarenkoA** [fe3dback/go-arch-lint#57]
Hi, when running the linter in Jenkins, I get the error "failed to load std packages". I checked the code, and it happens when loading the standard packages packages.Load(nil, "std"). It's unclear why this error occurs, and unfortunately, the root cause of the error is not visible. Maybe I need to wrap the returned error to get more details.

**Comment by fe3dback** [comment]
Hi, currently Golang has std package `golang.org/x/tools/go/packages`, that used for parse Golang code (and imports too).
But unfortunately, it requires Golang binary installed and available on the host machine.

This package run `go ..something..` underneath.

Linter itself didn’t know all existing std packages in your installed Golang version, because every version has different available std packages.

we have also a problem with image size, because of this:
https://github.com/fe3dback/go-arch-lint/issues/36

--

So, you need to have go binary installed in your environment

--

Maybe in future, go developers will make better ast lib, to parse go code, that will not require Golang binary installed on host. But currently, we can’t do anything about it.

**Comment by fe3dback** [comment]
hmm, you can try to add the '%v' error to a panic text at this line:
https://github.com/fe3dback/go-arch-lint/blob/master/internal/services/project/scanner/scanner.go#L42

and rerun patched linter in Jenkins.

With a detailed error, we can find this issue.

**Comment by LazarenkoA** [comment]
the PATH did not specify a path for go bin
